<?php
var_dump($this->jsLayout = isset($data['jsLayout']) && is_array($data['jsLayout']) ? $data['jsLayout'] : []);
?>



<div id="CrazyForm" data-bind="scope:'CrazyForm'">
    <!-- ko template: getTemplate() --><!-- /ko -->

</div>

<script type="text/x-magento-init">
    {
        "#CrazyForm": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        }
    }
</script>
